### ISSUE TITLE
Install Gazebo9

### ISSUE THREAD

**Issue by mauropasse** [alsora/ros2-code-examples#1]
To install succesfully Gazebo9, I've followed the steps here:

Alternative installation: step-by-step

http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install

**Comment by alsora** [comment]
I have checked and updated the instructions this morning, so they should work fine.
For reference, they also created a tutorial page for using gazebo with ROS2
http://gazebosim.org/tutorials?tut=ros2_installing&cat=connect_ros

**Comment by mauropasse** [comment]
The instructions work fine, no errors. But  I had the Gazebo 7.X installed (trying to get the 9.X), and after following the installation steps I still had the 7.X, that's why I followed the other installation steps which specifically install the 9.X version:
`sudo apt-get install gazebo9`
