### ISSUE TITLE
ros2 testing examples

### ISSUE THREAD

**Issue by simutisernestas** [alsora/ros2-code-examples#2]
Are there any plans on adding testing examples?

**Comment by alsora** [comment]
Hi,
do you mean to have a package that includes unit-tests, e.g. done using gtest?

**Comment by simutisernestas** [comment]
Basically yeah, there could be unit, integration tests, and examples of using `colcon test` and overall ros2 testing tools like `launch_testing` package, etc. I would like to contribute too, but I'm kind of new to these tools and I don't have a good idea about best practices in the space.
